### ISSUE TITLE
Doesn't work with ipad

### ISSUE THREAD

**Issue by strycker** [PoeticThemes/boo#4]
When I load this theme onto my blog, the main blog cover image fails to load

**Comment by strycker** [comment]
Clarification:  works on portrait orientation, issue is only with landscape mode

**Comment by eibt** [comment]
Hi Glenn, can you check if you can see the same issue in the demo? [https://boo-demo.tenoku.com](https://boo-demo.tenoku.com)

**Comment by eibt** [comment]
Also please check if you have extra code in the **code injection** section of your **admin area**, if so, try to remove it temporarily and check if the problem still shows up

**Comment by strycker** [comment]
Answering your second question first:  the only thing I have in the code injection is a link to google fonts.

Regarding the demo, the problem exists on there, too.  I'll try to attach screen shots from my iPad.  The first one is portrait mode (works) and the second is landscape (broken).

![img_0045](https://cloud.githubusercontent.com/assets/2963754/26232223/5edf21de-3c1a-11e7-859e-75b9298d41f4.PNG)

![img_0046](https://cloud.githubusercontent.com/assets/2963754/26232224/5ef0f1d4-3c1a-11e7-845d-f9b2f4c43960.PNG)

**Comment by eibt** [comment]
I applied a fix to this bug in the master branch, please download the theme from:
 [https://github.com/tenoku/boo/archive/master.zip](https://github.com/tenoku/boo/archive/master.zip)

Let me know if this solves the problem :)

**Comment by strycker** [comment]
Nope -- unfortunately it still doesn't work after downloading and
reinstalling.  Neither my site nor the demo page.  Broken in both Safari
and Chrome.

**Comment by eibt** [comment]
Can you please try the following steps to make sure it's not a caching issue:

Safari iOS
1. On your iPad, open the Safari app
2. [Turn on Private Browsing](https://support.apple.com/en-us/HT203036)
3. Visit your blog, check if the problem persists

Chrome iOS
1. On your iPad, open the Chrome app
2. [Open an Incognito window](https://support.google.com/chrome/answer/95464?co=GENIE.Platform%3DiOS&hl=en)
3. Visit your blog, check if the problem persists

Note: this patch is not yet applied to the demo at the time of writing this.

**Comment by strycker** [comment]
Tried both -- still doesn't work.

Note that I'm using an iPad Pro 9.7in, if the size of the screen matters for the bug.

**Comment by Krato** [comment]
Same error for me using iPad Air 2

**Comment by eibt** [comment]
Update: Tested the latest version with real devices on BrowserStack 👍

**iPad Pro 11 2018 (Safari)**
![captura de pantalla 2018-12-21 a las 8 27 19 p m](https://user-images.githubusercontent.com/5503784/50369708-53f35a00-055f-11e9-9c37-b7846ad9ab9e.png)
![captura de pantalla 2018-12-21 a las 8 27 08 p m](https://user-images.githubusercontent.com/5503784/50369710-5655b400-055f-11e9-869e-ba090ad35185.png)

**iPad Pro 11 2018 (Chrome)**
![captura de pantalla 2018-12-21 a las 8 35 38 p m](https://user-images.githubusercontent.com/5503784/50369757-15aa6a80-0560-11e9-9218-85d4c3b0f7ee.png)
![captura de pantalla 2018-12-21 a las 8 32 47 p m](https://user-images.githubusercontent.com/5503784/50369758-180cc480-0560-11e9-927f-1b32d800722d.png)

**iPad Air 2 (Safari)**
![captura de pantalla 2018-12-21 a las 8 39 59 p m](https://user-images.githubusercontent.com/5503784/50369801-ada85400-0560-11e9-8937-f9c4a8dc4ef9.png)
![captura de pantalla 2018-12-21 a las 8 39 46 p m](https://user-images.githubusercontent.com/5503784/50369802-af721780-0560-11e9-9b38-1e3440173900.png)

**iPad Air 2 (Chrome)**
![captura de pantalla 2018-12-21 a las 8 44 55 p m](https://user-images.githubusercontent.com/5503784/50369853-6e2e3780-0561-11e9-8c65-b0685864a367.png)
![captura de pantalla 2018-12-21 a las 8 43 13 p m](https://user-images.githubusercontent.com/5503784/50369855-72f2eb80-0561-11e9-93e5-44d180bc8162.png)

**Comment by strycker** [comment]
Awesome!  Thanks

**Comment by eibt** [comment]
@strycker If you get a chance to test it let me know! 👍
